[tools]
node = "latest"
"npm:@aikidosec/safe-chain" = "latest"

[settings]
experimental = true
trusted_config_paths = [
  "~/ghq/github.com/u1aryz",
  "~/go/src/github.com/u1aryz",
  "~/.config/dotfiles",
]
idiomatic_version_file_enable_tools = ["node"]
